socks5:
  listen: @PROXY_LOCAL_IP:@PROXY_LOCAL_PORT_SOCKS
http:
  listen: @PROXY_LOCAL_IP:@PROXY_LOCAL_PORT_HTTP
quic:
  init_to: 10s
  keepalive_period: 10s
bandwidth:
  up: 50 mbps
  down: 100 mbps
fast_open: true
lazy: true